### ISSUE TITLE
Add text regarding preferred file types to the dataset upload page

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#100]
Let's add this text to appear after the "File upload size is limited to 2 GB.":

"Please use a pdf format for documents and a csv format for table-based data. These file types increase portability and permits preview on the repository."

![image](https://cloud.githubusercontent.com/assets/5023186/12964886/bc47e1e4-d00f-11e5-9f90-715b903380a8.png)

**Comment by pkdash** [comment]
@AmberSJones I have made this fix and you can test it on production server.

**Comment by AmberSJones** [comment]
Can you edit the text- it should say 'permit' instead of 'permits'. I know that's my fault- sorry for the typo.

**Comment by pkdash** [comment]
Done

**Comment by AmberSJones** [comment]
Thanks.
