### ISSUE TITLE
Change Username

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#101]
Is it possible to change a username? I currently cannot see a way for the User or an Admin to do it.

**Comment by horsburgh** [comment]
What is the use case/need for this that makes it high priority?

**Comment by AmberSJones** [comment]
It has been requested by a users. The case is that an individual user has created an account with some datasets. The user then wants to assign those datasets to a group- I think they are trying to get around the issue where only a single user can edit a dataset by creating a shared 'group' account. We could recommend this to those who are looking for a way to allow multiple users to edit a dataset.
![image](https://cloud.githubusercontent.com/assets/5023186/13397844/f1cab442-deb8-11e5-8125-e57b230d02ed.png)

**Comment by pkdash** [comment]
@AmberSJones It should be possible to change user name. See this link (http://docs.ckan.org/en/latest/sysadmin-guide.html#managing-users)

**Comment by AmberSJones** [comment]
I cannot find the option to 'Manage' a user account on our site. Maybe we can look at it together today.

**Comment by AmberSJones** [comment]
As a sysadmin, I can get to the page where I can edit a user's account, including username, but when I attempt to do so, I get a Server Error:

![image](https://cloud.githubusercontent.com/assets/5023186/13495064/a12b57f4-e105-11e5-8091-c9ee54cc2e84.png)


![image](https://cloud.githubusercontent.com/assets/5023186/13495047/8981f36a-e105-11e5-9d91-dc6849d44689.png)

**Comment by AmberSJones** [comment]
This is still outstanding- I'd like to get it resolved if we can.

**Comment by pkdash** [comment]
@AmberSJones I was not able to reproduce this error. I created a user called "User One" and was able to change username and password for this user. See if  you can change the username for 'User One'.

**Comment by AmberSJones** [comment]
I was able to change the username for 'User One', but I still cannot change the username for mlbarnes. I keep getting server error. Is it because we have changed the schema somehow? Is it because that username is associated with some datasets?

**Comment by pkdash** [comment]
@AmberSJones What's the full name of the user for whom you can't change the username?

**Comment by AmberSJones** [comment]
See the above screenshot. The full name is 'Beth Neilson Group'. The current username is mlbarnes, but we need to change it to BTNGroup.

**Comment by pkdash** [comment]
@AmberSJones It seems the username has to be lowercase.

**Comment by AmberSJones** [comment]
Oh goodness. I'm glad you got that figured out! I'll close this issue.
