### ISSUE TITLE
Photo Upload

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#102]
Are there ways to upload a picture other than the Gravatar website? Users may want to add  photos without using that website functionality.

**Comment by horsburgh** [comment]
I think the answer is no unless we implement it. Right now if we invest time in the repository, it needs to be in formal publication and DOI registration. We should focus on that first.

**Comment by AmberSJones** [comment]
That's fine- it was requested by a user. I should clarify that the question is high priority. The functionality is not high priority.

**Comment by AmberSJones** [comment]
Ok- I'm closing this as we aren't going to devote development time to it.
