### ISSUE TITLE
Additional Alignment Issue

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#82]
I've found a few additional alignment issues- these may not be ones to fix this week. 
On the dataset page:
The text and check box should be aligned vertically.
![image](https://cloud.githubusercontent.com/assets/5023186/3509390/2cb21af8-069a-11e4-9094-67bcac50499d.png)
The word 'citation' should be aligned vertically with the text of the citation. Or it could be above it and the citation could be left aligned.
![image](https://cloud.githubusercontent.com/assets/5023186/3509391/348f5d8a-069a-11e4-8656-2981e36baa40.png)

**Comment by pkdash** [comment]
@AmberSJones Is this still an issue? 


![image](https://cloud.githubusercontent.com/assets/2523434/15086205/6ddcbed2-139c-11e6-8f12-ed072e867bb8.png)

**Comment by AmberSJones** [comment]
Both look good.
