### ISSUE TITLE
Usage Tracking

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#88]
We need to implement usage tracking using Google Analytics. @jcaraballo17 , can you set it up for this site (repository.iutahepscor.org) also?

**Comment by pkdash** [comment]
@AmberSJones It seems CKAN already has some builtin analytics that you find here (http://repository.iutahepscor.org/stats). Do we need more than that?

**Comment by AmberSJones** [comment]
Yes- those stats are cool, but they don't tell us anything about how many views or downloads have been done on our datasets.

@horsburgh , these plots might be cool for your AAAS presentation?

**Comment by horsburgh** [comment]
Yes - Amber hit the nail on the head. CKAN seems a bit backward about what is important. What I need to know is how are users of the website interacting with the data (views, downloads, etc.) rather than how the data publishers are interacting.

I didn't even know this page existed...

**Comment by pkdash** [comment]
@AmberSJones I have implemented this based on code I got from Juan. Not sure how you can test it though.

**Comment by AmberSJones** [comment]
I'm closing this- I'll talk with @jcaraballo17  on some ideas for testing.
