### ISSUE TITLE
Example Text for N/S/E/W Extents

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#90]
We need to add some example text for N/S/E/W Extents on the metadata page. I suggest the below:

North Extent: e.g., 41.75765
South Extent: e.g., 40.48343
East Extent: e.g., -111.88232
West Extent: e.g., -111.48117

**Comment by pkdash** [comment]
Have implemented this on the sandbox server (http://iutah-ckan-test.uwrl.usu.edu/). Once @AmberSJones tests it there I can update the production server with this fix.

**Comment by AmberSJones** [comment]
Looks great. Push to production.
