### ISSUE TITLE
Add links to tutorial videos on the homepage

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#95]
We need to add links to the data publication tutorial videos to the repository homepage. Let's discuss where these should live and where links should be.

**Comment by AmberSJones** [comment]
I am posting these videos to the Cube in Public/Tutorials. One the repository homepage, we want to move the 'Search Your Data' link to the top and then include links to the videos below that box. @pkdash, can you do this?

**Comment by pkdash** [comment]
Yes, I can do it.

**Comment by AmberSJones** [comment]
Ok- we're going to coordinate this with the storage and posting of the videos on data.iutahepscor.org. @marioscience , if you will create in django a url for each video and we can point to the urls on the ckan website. @pkdash will coordinate with you.

**Comment by pkdash** [comment]
@AmberSJones it is ready for testing on the production server.

**Comment by AmberSJones** [comment]
Minor changes: needs a comma after 'discover' and needs slightly larger margins on the right side.

**Comment by pkdash** [comment]
Made these minor changes.

**Comment by AmberSJones** [comment]
Thanks, @pkdash .
