### ISSUE TITLE
Change the way we are handling 'Variables'

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#96]
We're considering changing the way we are handling variables:
1. Implement a required text field to describe variables
2. Make 'Variable' and 'Unit' not required, but still optional

@pkdash , how hard would this be to implement? The issue here is that we have existing datasets that do not currently include what would be a required field.

**Comment by pkdash** [comment]
@AmberSJones As I understand we will now have an additional field for each variable called  'Variable Description' which will require an entry. It is hard in the sense that anytime we make any changes to metadata I have to do quite a bit of testing to make sure nothing got broken. In regards to existing datasets we can enforce data entry for variable description when the dataset is updated for any reason. Additionally, we can put a default string like "variable description missing' for the existing datatsets.

**Comment by AmberSJones** [comment]
I've tested the newly implemented field on the test server. The issue I'm observing is that the datasets have this warning: 'This dataset was created with an older metadata schema. It needs to be updated before any of its resources can be accessed.' After the metadata record is completed, I am unable to add resources because 'This dataset needs its metadata updated before resources can be added or edited. Use the fields and the Update Dataset button on this page to update.'  However, all of the required metadata (including the new field) is already complete.

I think it may still be requiring the Observed Variable Name and Units because if I add one to the metadata, I don't receive the warnings.

**Comment by pkdash** [comment]
I can see this problem. Working to fix it.

**Comment by pkdash** [comment]
I have now updated the code on the test server. @AmberSJones Please test to see if it got fixed.

**Comment by AmberSJones** [comment]
Yes, but... if use the Observed Variable Name and Units and then try to remove them all, I get an error. Otherwise seems good.

![image](https://cloud.githubusercontent.com/assets/5023186/7437679/e33b7cea-f016-11e4-8daf-667151dbf8f3.png)

**Comment by pkdash** [comment]
There has to be one metadata element displayed even if the data entry for that is optional in order to be able to add a new element of that type (this is the case of repeatable element). I think this can be changed with some javascript if we really want to avoid this message box.

**Comment by AmberSJones** [comment]
That mostly seems ok, but then we will not be able to remove all of the Observed Variable Name/Units for the existing datasets for which we need to update the metadata elements.

**Comment by pkdash** [comment]
For existing datasets, you can remove all of the Observed Variable Name/Units fields except the last one pair. The last one you can't delete but you can delete the name/unit values inside the fields.

**Comment by AmberSJones** [comment]
Ok- that should work. Let's push this to production.

**Comment by pkdash** [comment]
We will push the changes tonight as I have to restart the web server.

**Comment by pkdash** [comment]
Production server has been updated with this fix.
