### ISSUE TITLE
Make links for optional metadata more obvious

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#97]
Several users have been entering metadata records and inadvertently skipped over the links that expand the optional metadata. They have requested that we make these more obvious.

**Comment by pkdash** [comment]
@AmberSJones - Any suggestions how we should make it more obvious.

**Comment by AmberSJones** [comment]
Improve the styling somehow... bigger text? Add an arrow or +/- signs to indicate collapse/expand. @mauriel133 might have some ideas.

**Comment by AmberSJones** [comment]
We determined that we should simply keep the expandable elements open by default. A user can collapse if desired.

**Comment by pkdash** [comment]
@AmberSJones I have made this fix and you can test it on production server.

**Comment by AmberSJones** [comment]
Great. Closing.
