### ISSUE TITLE
Private datasets publically viewable

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#98]
It is possible for regular (non-admin) users to view private (and even deleted) datasets. This is done by clicking on 'Users' and then selecting a user's profile. Any- even private and even deleted- datasets created by that user are visible.

'Users' is only visible via the navigation at the top of the screen when a user selects their own profile. This is buried pretty deep, but we need to try and address it.

![image](https://cloud.githubusercontent.com/assets/5023186/11384886/0d4c1cf8-92d1-11e5-8bf8-6a0471c44eb2.png)

**Comment by pkdash** [comment]
@AmberSJones Will look into it.

**Comment by pkdash** [comment]
@AmberSJones I am not able to reproduce this. As a non-admin user I can see only my private resources.

![image](https://cloud.githubusercontent.com/assets/2523434/15085757/716e0f90-1399-11e6-9e41-83ded53077ed.png)

**Comment by AmberSJones** [comment]
Ok- here is the workflow to reproduce this error.
1. Logged in as an editor, click on your own user profile.
2. Click on 'Users' in the navigation at the top of the screen.
3. Select a user. (You could try Enjie Li - she is someone who has private datasets currently).
4. For that user, all of the datasets, even the private ones are visible.

![image](https://cloud.githubusercontent.com/assets/5023186/15087754/49fd28c8-13a9-11e6-89ed-4c2c55243fbd.png)

**Comment by pkdash** [comment]
@AmberSJones I have applied the fix to the server. Bit it seems I need to restart the server for this fix to work. At this point trying to view user profile will raise "Server Error". I will restart the server tonight.

**Comment by pkdash** [comment]
@AmberSJones Please test to see if this issue has been fixed now.

**Comment by AmberSJones** [comment]
Yes, great!
